<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="vagrant" failures="1" tests="1" name="com.learning.runner.BugZillaRunner" time="5.583" errors="0" timestamp="2025-03-29T10:03:18 UTC" skipped="0">
  <testcase classname="com.learning.runner.BugZillaRunner" name="runScenario" time="5.583">
    <failure message="expected [Bugzilla – Main Page] but found [Log in to Bugzilla]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Bugzilla – Main Page] but found [Log in to Bugzilla]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.learning.stepdfn.StepDefinition.page_should_be_open_wth_title(StepDefinition.java:40)
at ✽.Page should be open wth title "Bugzilla – Main Page"(file:///home/vagrant/nirvana/chaintestreporting/cucumberintegration/src/test/resources/features/BgzillaAutomation.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- com.learning.runner.BugZillaRunner -->
